spring:
  liquibase:
    enabled: false
    contexts: ${spring.profiles.active}
    database-change-log-table: Z_LIQ_CHANGELOG
    database-change-log-lock-table: Z_LIQ_CHANGELOG_LOCK
    change-log: classpath:com/omnia/liquibase/liquibase-master.xml

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_enum_type: STRING

logging:
  level:
    liquibase: INFO