spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect